//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminAction()
        {
            this.AdminGroupAction_Map = new HashSet<AdminGroupAction_Map>();
            this.AdminUser_Action_Default = new HashSet<AdminUser_Action_Default>();
            this.AdminUser_PlusAction = new HashSet<AdminUser_PlusAction>();
            this.AdminUser_Action_Deny = new HashSet<AdminUser_Action_Deny>();
        }
    
        public int AId { get; set; }
        public int CId { get; set; }
        public string ActionName { get; set; }
        public string ActionDisplayName { get; set; }
        public string CssIcon { get; set; }
        public bool ShowMenuStatus { get; set; }
        public bool PublicStatus { get; set; }
        public int Sort { get; set; }
        public bool Visible { get; set; }
        public bool IsDefault { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> GaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminGroupAction_Map> AdminGroupAction_Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser_Action_Default> AdminUser_Action_Default { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser_PlusAction> AdminUser_PlusAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser_Action_Deny> AdminUser_Action_Deny { get; set; }
        public virtual AdminController AdminController { get; set; }
    }
}
