//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministrativeUnit
    {
        public int AdministrativeUnitsId { get; set; }
        public string AdministrativeUnitsVN { get; set; }
        public string AdministrativeUnitsEN { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> LevelNo { get; set; }
        public string LevelPath { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Prefix { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
