//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppList
    {
        public int AppListId { get; set; }
        public string AppListCode { get; set; }
        public Nullable<int> EntryNo { get; set; }
        public string NameVI { get; set; }
        public string NameEN { get; set; }
        public string Description { get; set; }
        public string FunctionDescription { get; set; }
        public Nullable<int> PnLListId { get; set; }
        public string BUCode { get; set; }
        public Nullable<int> VendorType { get; set; }
        public string VendorCode { get; set; }
        public string Platform { get; set; }
        public string DevOwner { get; set; }
        public string OperationCentrer { get; set; }
        public string OperationDepartment { get; set; }
        public string OperationGroup { get; set; }
        public string OperationOwner { get; set; }
        public Nullable<int> AppType { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<bool> SAP { get; set; }
        public Nullable<int> Status { get; set; }
        public string URL { get; set; }
        public Nullable<int> AuthenticationMethod { get; set; }
        public Nullable<int> Rand { get; set; }
        public Nullable<int> RTO { get; set; }
        public Nullable<int> RPO { get; set; }
        public string RLO { get; set; }
        public Nullable<int> DR { get; set; }
        public Nullable<System.DateTime> LastDRTest { get; set; }
        public Nullable<int> SCStatus { get; set; }
        public Nullable<System.DateTime> YearImplement { get; set; }
        public Nullable<int> Stability { get; set; }
        public string NumberOfActiveUser { get; set; }
        public string ConcurrentUser { get; set; }
        public string BusinessHour { get; set; }
        public string BusinessPainPoints { get; set; }
        public string TechnologyPainPoints { get; set; }
        public string MaintenanceWindows { get; set; }
        public Nullable<bool> DevTestEnvironment { get; set; }
        public string HostingLocation { get; set; }
        public Nullable<bool> ToBeReplaced { get; set; }
        public Nullable<int> ReplacedBy { get; set; }
        public string DetailReplacedBy { get; set; }
        public Nullable<bool> SecurityRequirement { get; set; }
        public Nullable<bool> SecurityDesign { get; set; }
        public Nullable<bool> CertificationCheck { get; set; }
        public Nullable<bool> SecurityTesting { get; set; }
        public Nullable<bool> RiskAssessment { get; set; }
        public Nullable<int> SecurityStatus { get; set; }
        public Nullable<int> Performance { get; set; }
        public string PerformanceNote { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
