//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckList()
        {
            this.CheckListDetails = new HashSet<CheckListDetail>();
            this.CheckListItemMaps = new HashSet<CheckListItemMap>();
            this.CheckListMaps = new HashSet<CheckListMap>();
            this.CheckListSystems = new HashSet<CheckListSystem>();
        }
    
        public int CheckListId { get; set; }
        public string CheckListName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> Priority { get; set; }
        public int SystemId { get; set; }
        public int CheckListTypeId { get; set; }
        public bool IsSync { get; set; }
        public Nullable<System.DateTime> DateSync { get; set; }
        public System.DateTime SetupDateFrom { get; set; }
        public bool IsProcess { get; set; }
    
        public virtual CheckListType CheckListType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListDetail> CheckListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListItemMap> CheckListItemMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListMap> CheckListMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListSystem> CheckListSystems { get; set; }
        public virtual SystemCheckList SystemCheckList { get; set; }
    }
}
