//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListOperationLog
    {
        public long LogId { get; set; }
        public Nullable<long> InstanceId { get; set; }
        public Nullable<int> CheckListStatusIdOle { get; set; }
        public Nullable<int> CheckListStatusIdNew { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual CheckListOperation CheckListOperation { get; set; }
    }
}
