//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckListOperation()
        {
            this.CheckListOperationLogs = new HashSet<CheckListOperationLog>();
            this.CheckListOperationMappings = new HashSet<CheckListOperationMapping>();
        }
    
        public long InstanceId { get; set; }
        public int SystemId { get; set; }
        public int CheckListId { get; set; }
        public int CheckListTypeId { get; set; }
        public string CheckListName { get; set; }
        public int CheckListStatusId { get; set; }
        public System.DateTime SetupDateFrom { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListOperationLog> CheckListOperationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListOperationMapping> CheckListOperationMappings { get; set; }
        public virtual SystemCheckList SystemCheckList { get; set; }
    }
}
