//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public System.Guid Id { get; set; }
        public string ViName { get; set; }
        public string EnName { get; set; }
        public string Code { get; set; }
        public string HospitalCode { get; set; }
        public Nullable<System.Guid> SpecialtyId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public bool IsActivated { get; set; }
    }
}
