//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.AdminUser_Location = new HashSet<AdminUser_Location>();
            this.Devices = new HashSet<Device>();
            this.Location1 = new HashSet<Location>();
        }
    
        public int LocationId { get; set; }
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        public string SloganVN { get; set; }
        public string SloganEN { get; set; }
        public string LogoName { get; set; }
        public string BackgroundName { get; set; }
        public string ColorCode { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int LevelNo { get; set; }
        public string LevelPath { get; set; }
        public Nullable<int> RootId { get; set; }
        public Nullable<int> LayoutTypeId { get; set; }
        public Nullable<int> QuestionGroupId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SourceClientId { get; set; }
        public string ORUnitName { get; set; }
        public string ORUnitEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser_Location> AdminUser_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Location1 { get; set; }
        public virtual Location Location2 { get; set; }
    }
}
