//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogObject
    {
        public long Id { get; set; }
        public long ObjectId { get; set; }
        public Nullable<int> OldState { get; set; }
        public Nullable<int> NewState { get; set; }
        public int ObjectTypeId { get; set; }
        public int ActionId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserAssigned { get; set; }
        public string OldInformation { get; set; }
        public string NewInformation { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
