//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORAnesthProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORAnesthProgress()
        {
            this.ORMappingEkips = new HashSet<ORMappingEkip>();
            this.ORTrackings = new HashSet<ORTracking>();
        }
    
        public int Id { get; set; }
        public string PId { get; set; }
        public string HospitalCode { get; set; }
        public string HospitalName { get; set; }
        public int HpServiceId { get; set; }
        public int ORRoomId { get; set; }
        public Nullable<System.DateTime> dtStart { get; set; }
        public Nullable<System.DateTime> dtEnd { get; set; }
        public Nullable<System.DateTime> dtOperation { get; set; }
        public Nullable<int> TimeAnesth { get; set; }
        public string RegDescription { get; set; }
        public int State { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string SurgeryDescription { get; set; }
        public string AnesthDescription { get; set; }
        public string NameProject { get; set; }
        public string VisitCode { get; set; }
        public Nullable<int> UIdPTVMain { get; set; }
        public Nullable<int> UIdPTVSub1 { get; set; }
        public Nullable<int> UIdPTVSub2 { get; set; }
        public Nullable<int> UIdPTVSub3 { get; set; }
        public Nullable<int> UIdCECDoctor { get; set; }
        public Nullable<int> UIdNurseTool1 { get; set; }
        public Nullable<int> UIdNurseTool2 { get; set; }
        public Nullable<int> UIdNurseOutRun1 { get; set; }
        public Nullable<int> UIdNurseOutRun2 { get; set; }
        public Nullable<int> UIdMainAnesthDoctor { get; set; }
        public Nullable<int> UIdSubAnesthDoctor { get; set; }
        public Nullable<int> UIdAnesthNurse1 { get; set; }
        public Nullable<int> UIdAnesthNurse2 { get; set; }
        public Nullable<bool> IsEmergence { get; set; }
        public int Sorting { get; set; }
        public bool IsSync { get; set; }
        public Nullable<System.DateTime> DateSync { get; set; }
        public bool IsProcess { get; set; }
        public string OrderID { get; set; }
        public string ChargeDetailId { get; set; }
        public Nullable<int> UIdAnesthNurseRecovery { get; set; }
        public Nullable<System.DateTime> dtExtend { get; set; }
        public Nullable<int> UIdNurseOutRun3 { get; set; }
        public Nullable<int> UIdNurseOutRun4 { get; set; }
        public Nullable<int> UIdNurseOutRun5 { get; set; }
        public Nullable<int> UIdNurseOutRun6 { get; set; }
        public Nullable<int> UIdPTVSub4 { get; set; }
        public Nullable<int> UIdPTVSub5 { get; set; }
        public Nullable<int> UIdPTVSub6 { get; set; }
        public Nullable<int> UIdPTVSub7 { get; set; }
        public Nullable<int> UIdPTVSub8 { get; set; }
        public Nullable<int> SurgeryType { get; set; }
        public string Diagnosis { get; set; }
        public string AdmissionWard { get; set; }
        public Nullable<System.DateTime> dtAdmission { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public string ChargeBy { get; set; }
        public Nullable<int> UIdKTVSubSurgery { get; set; }
        public Nullable<int> UIdKTVDiagnose { get; set; }
        public Nullable<int> UIdKTVCEC { get; set; }
        public Nullable<int> UIdDoctorDiagnose { get; set; }
        public Nullable<int> UIdDoctorNewBorn { get; set; }
        public Nullable<int> UIdMidwives { get; set; }
        public Nullable<int> UIdAnesthesiologist { get; set; }
        public Nullable<int> UIdSubAnesthDoctor2 { get; set; }
    
        public virtual ORRoom ORRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORMappingEkip> ORMappingEkips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORTracking> ORTrackings { get; set; }
    }
}
