//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OROperationLink
    {
        public long Id { get; set; }
        public System.Guid Guid { get; set; }
        public string Code { get; set; }
        public System.DateTime LimitDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> dtActive { get; set; }
        public string IpActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
