//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string PId { get; set; }
        public Nullable<int> Age { get; set; }
        public string AreaName { get; set; }
        public string EkipName { get; set; }
        public string TypeName { get; set; }
        public string ServiceName { get; set; }
        public int State { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int Sorting { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string PatientName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TypeKcbId { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> IntendTime { get; set; }
        public Nullable<int> LichHen_Id { get; set; }
        public bool IsEmergence { get; set; }
        public string EKipAnesth { get; set; }
        public Nullable<int> id_ehos_room { get; set; }
    
        public virtual RoomHospital RoomHospital { get; set; }
    }
}
