//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteList
    {
        public int SiteListId { get; set; }
        public string SiteListCode { get; set; }
        public string PnLCode { get; set; }
        public string PnLBUCode { get; set; }
        public string Description { get; set; }
        public string ReferCode { get; set; }
        public Nullable<int> Status { get; set; }
        public string FullName { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Address { get; set; }
        public string Manager { get; set; }
        public string ManagerPhone { get; set; }
        public string SitePhone { get; set; }
        public string SiteMail { get; set; }
        public string AreaManager { get; set; }
        public string AreaManagerPhone { get; set; }
        public string AreaManagerMail { get; set; }
        public string ITOpDepartment { get; set; }
        public string ITOpGroup { get; set; }
        public string ITOpStaff { get; set; }
        public Nullable<int> BigSiteId { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
