//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteOpeningList
    {
        public int SiteOpeningListId { get; set; }
        public Nullable<int> EntryNo { get; set; }
        public Nullable<int> PnLListId { get; set; }
        public Nullable<int> PnLBUListId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string PICName { get; set; }
        public string PICPhone { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string FullAddress { get; set; }
        public string Note { get; set; }
        public string RefCode { get; set; }
        public Nullable<int> BigSiteCodeId { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
