//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemDataChangeLogDetail
    {
        public int LdcdId { get; set; }
        public int LdcId { get; set; }
        public string ChangedFieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual SystemDataChangeLog SystemDataChangeLog { get; set; }
    }
}
