//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemCheckList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemCheckList()
        {
            this.AdminUser_System = new HashSet<AdminUser_System>();
            this.CheckLists = new HashSet<CheckList>();
            this.CheckListSystems = new HashSet<CheckListSystem>();
            this.CheckListOperations = new HashSet<CheckListOperation>();
        }
    
        public int SystemId { get; set; }
        public string SystemName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Code { get; set; }
        public Nullable<int> PlId { get; set; }
        public string SystemNameEn { get; set; }
        public int CateId { get; set; }
        public int SubCateId { get; set; }
        public string FunctionOverview { get; set; }
        public string ProviderName { get; set; }
        public int OriginTypeId { get; set; }
        public string Platform { get; set; }
        public int AppTypeId { get; set; }
        public bool IsSAP { get; set; }
        public int State { get; set; }
        public string UrlSystem { get; set; }
        public int AuthenticationMethodId { get; set; }
        public int RankId { get; set; }
        public int RTOTypeId { get; set; }
        public int RPOTypeId { get; set; }
        public Nullable<int> RLO { get; set; }
        public int DRTypeId { get; set; }
        public Nullable<System.DateTime> LastDateDRTest { get; set; }
        public int ScStateId { get; set; }
        public string SME { get; set; }
        public string OwingBusinessUnit { get; set; }
        public string ITContact { get; set; }
        public Nullable<int> YearImplement { get; set; }
        public int StabilityId { get; set; }
        public int QuantityUserActive { get; set; }
        public int ConCurrentUser { get; set; }
        public string BusinessHour { get; set; }
        public string BusinessIssue { get; set; }
        public string TechIssue { get; set; }
        public string SystemMaintainTime { get; set; }
        public bool IsDevTest { get; set; }
        public string HostingLocation { get; set; }
        public bool IsReplace { get; set; }
        public Nullable<int> ReplaceBy { get; set; }
        public string DetailReplaceBy { get; set; }
        public bool IsRequirementSecurity { get; set; }
        public bool IsRequirementSecurityDesign { get; set; }
        public bool IsCheckCertification { get; set; }
        public bool IsCheckSecurityByGolive { get; set; }
        public bool IsCheckRisk { get; set; }
        public int SecurityStateId { get; set; }
        public int PerformanceId { get; set; }
        public string PerformanceNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser_System> AdminUser_System { get; set; }
        public virtual CateSystem CateSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckList> CheckLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListSystem> CheckListSystems { get; set; }
        public virtual SubCateSystem SubCateSystem { get; set; }
        public virtual PnLList PnLList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListOperation> CheckListOperations { get; set; }
    }
}
