//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRuntimeLog
    {
        public System.Guid Id { get; set; }
        public string LogContent { get; set; }
        public byte LogType { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int SourceId { get; set; }
    }
}
