//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLichHen_Temp
    {
        public int IDKey { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> Ehos_Iddv { get; set; }
        public string PId { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> id_ehos_room { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> ThoiGianHen_BatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianHen_KetThuc { get; set; }
        public Nullable<int> Typel { get; set; }
    }
}
